"""Render an optimized DSPy artifact in various target formats.

Each renderer takes (artifact, metadata) and produces a string suitable for
writing to a file. Provenance footer on every output so downstream agents
can trace the source.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone


def _utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _provenance_block(metadata: dict) -> dict:
    """Compact metadata for the skill frontmatter / footer."""
    return {
        "optimized_module_id": metadata.get("id"),
        "module_type": metadata.get("module_type"),
        "optimizer": metadata.get("optimizer_used")
                    or metadata.get("optimizer_name"),
        "task_lm": metadata.get("task_lm") or "(unrecorded)",
        "reflection_lm": metadata.get("reflection_lm") or "(none)",
        "score": metadata.get("metric_after") or metadata.get("score"),
        "trainset_size": metadata.get("trainset_size"),
        "created_at": metadata.get("created_at"),
        "rendered_at": _utc_iso(),
    }


def render_skill(artifact: dict, metadata: dict,
                 skill_name: str = "sio-rule-generator") -> str:
    """Render a Claude Code skill (.md with YAML frontmatter)."""
    prov = _provenance_block(metadata)
    score = prov["score"]
    score_str = f"{score:.4f}" if isinstance(score, (int, float)) else str(score)
    optimizer = prov["optimizer"] or "?"
    created = prov["created_at"] or "?"

    desc = (
        f"SIO-distilled CLAUDE.md rule generator. Given a Claude Code error "
        f"pattern (pattern_description + example_errors + project_context), "
        f"produces a concise, testable rule. "
        f"Optimized by SIO {optimizer.upper()} {created[:10]}, score={score_str}."
    )

    instr = artifact.get("instruction", "")
    fields = artifact.get("fields", [])
    demos = artifact.get("demos", [])

    # YAML frontmatter
    lines = [
        "---",
        f"name: {skill_name}",
        f'description: "{desc}"',
        "user-invocable: true",
        "metadata:",
    ]
    for k, v in prov.items():
        if isinstance(v, str):
            lines.append(f"  {k}: \"{v}\"")
        else:
            lines.append(f"  {k}: {v if v is not None else 'null'}")
    lines.append("---")
    lines.append("")
    lines.append(f"# {skill_name} (SIO-distilled)")
    lines.append("")
    lines.append(f"> Auto-generated by `sio render`. Optimized by SIO "
                 f"`{optimizer}` (score={score_str}) on {created[:10]}.")
    lines.append("")
    lines.append("## Input contract")
    lines.append("")
    if fields:
        for f in fields:
            prefix = f.get("prefix", "?") if isinstance(f, dict) else str(f)
            description = (f.get("description", "") if isinstance(f, dict) else "")
            lines.append(f"- **{prefix}** — {description}")
        lines.append("")
    lines.append("## System instruction (the learned prompt)")
    lines.append("")
    lines.append(instr)
    lines.append("")

    if demos:
        lines.append("## Few-shot demonstrations")
        lines.append("")
        for i, d in enumerate(demos[:10], 1):
            lines.append(f"### Example {i}")
            for k, v in (d.items() if isinstance(d, dict) else []):
                lines.append(f"**{k}:** {v}")
            lines.append("")

    lines.append("## Provenance")
    lines.append("")
    lines.append(f"- Source artifact: `~/.sio/optimized/*__{optimizer}__*.json`")
    lines.append(f"- Source DB row: `optimized_modules.id = {prov['optimized_module_id']}`")
    lines.append(f"- Task LM: `{prov['task_lm']}`")
    lines.append(f"- Reflection LM: `{prov['reflection_lm']}`")
    lines.append(f"- Score (metric_after): `{score_str}`")
    lines.append(f"- Rendered at: `{prov['rendered_at']}`")
    return "\n".join(lines) + "\n"


def render_system_prompt(artifact: dict, metadata: dict) -> str:
    """Flat string suitable for any LM SDK's `system_prompt=` argument."""
    instr = artifact.get("instruction", "")
    demos = artifact.get("demos", [])
    out = [instr.strip()]
    if demos:
        out.append("\n## Examples")
        for i, d in enumerate(demos[:5], 1):
            out.append(f"### Example {i}")
            for k, v in (d.items() if isinstance(d, dict) else []):
                out.append(f"{k}: {v}")
    score = metadata.get("metric_after") or metadata.get("score") or "?"
    score_str = f"{score:.4f}" if isinstance(score, (int, float)) else str(score)
    out.append(f"\n\n[Source: SIO module id={metadata.get('id')}, "
               f"optimizer={metadata.get('optimizer_used')}, score={score_str}]")
    return "\n".join(out)


def render_claude_md(artifact: dict, metadata: dict) -> str:
    """Rule-injection format: standalone Markdown section, no frontmatter."""
    skill_body = render_skill(artifact, metadata)
    # Strip the leading YAML frontmatter
    if skill_body.startswith("---"):
        end = skill_body.find("---", 3)
        if end > 0:
            skill_body = skill_body[end+3:].lstrip("\n")
    return skill_body


def render_json_prompt(artifact: dict, metadata: dict) -> str:
    """Programmatic JSON payload for HTTP agents."""
    return json.dumps({
        "system": artifact.get("instruction", ""),
        "few_shot_examples": artifact.get("demos", []),
        "input_fields": [
            f.get("prefix") if isinstance(f, dict) else str(f)
            for f in artifact.get("fields", [])
        ],
        "metadata": _provenance_block(metadata),
    }, indent=2)
