"""PreToolUse hook generator + ``~/.claude/settings.json`` registrar.

Phase 4 of ``prds/prd-violated-rule-to-pretooluse-hook.md``. Takes the
structured :class:`DetectionPattern` from Phase 3 and produces an
executable Python hook script under
``~/.claude/hooks/sio-promoted/<slug>.py``, then merges a
``PreToolUse`` registration into the user's existing
``~/.claude/settings.json`` without disturbing other hooks.

The generated hook script self-contains every dependency it needs —
no SIO import path required at hook runtime. This means a user can
delete SIO from their environment and the promoted hook still runs.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import sqlite3
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from sio.promote_rule.extractor import DetectionPattern


# ---------------------------------------------------------------------------
# Hook script template — string formatted with the rule + detection details.
# Kept as a single triple-quoted block for easy review; uses %s placeholders
# (not f-strings or .format) so the script body itself can contain {} freely.
# ---------------------------------------------------------------------------

_HOOK_TEMPLATE = '''\
#!/usr/bin/env python3
"""SIO-promoted PreToolUse hook.

Rule:           {rule_text!r}
Source:         {rule_source_file}:{rule_source_line}
Promoted at:    {promoted_at}
Mode:           {mode}
Rationale:      {rationale}

Generated by `sio promote-rule` (see prds/prd-violated-rule-to-pretooluse-hook.md).
Do not edit by hand — re-run the CLI with --mode block to flip enforcement,
or run `sio rollback-hook <id>` to remove (TBD in Phase 6).
"""
import json
import sys
from pathlib import Path

# --- detection contract (filled by sio promote-rule) ----------------------

RULE_TEXT       = {rule_text!r}
DETECTION_EXPR  = {detection_expr!r}
MATCHER_TOOLS   = {matcher_tools!r}      # [] = wildcard; harness matcher is the primary filter
MODE            = {mode!r}                  # "warn" | "block"
WINDOW_SIZE     = 5                          # rolling tool-call history per session

# --- session state (persists tool history across hook invocations) --------

def _state_path(session_id: str) -> Path:
    base = Path.home() / ".claude" / ".sio-promoted-state"
    base.mkdir(parents=True, exist_ok=True)
    safe = "".join(c for c in (session_id or "unknown") if c.isalnum() or c in "-_") or "unknown"
    return base / f"{{safe}}.json"

def _load_state(session_id: str) -> dict:
    p = _state_path(session_id)
    if not p.exists():
        return {{"recent_tool_names": [], "recent_tool_inputs": []}}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {{"recent_tool_names": [], "recent_tool_inputs": []}}

def _save_state(session_id: str, state: dict) -> None:
    try:
        _state_path(session_id).write_text(json.dumps(state), encoding="utf-8")
    except Exception:
        pass  # state failure must never crash the hook

# --- main -----------------------------------------------------------------

def main() -> None:
    try:
        payload = json.loads(sys.stdin.read() or "{{}}")
    except Exception:
        sys.stdout.write(json.dumps({{"action": "allow"}}))
        return

    tool_name = payload.get("tool_name", "") or ""
    tool_input = payload.get("tool_input", {{}}) or {{}}
    if not isinstance(tool_input, dict):
        tool_input = {{}}
    session_id = payload.get("session_id", "") or "unknown"

    # Defense in depth — harness matcher should already filter, but bail
    # cleanly if we somehow receive a tool we don't watch.
    if MATCHER_TOOLS and tool_name not in MATCHER_TOOLS:
        sys.stdout.write(json.dumps({{"action": "allow"}}))
        return

    state = _load_state(session_id)
    recent_tool_names = state.get("recent_tool_names", [])
    recent_tool_inputs = state.get("recent_tool_inputs", [])

    fires = False
    try:
        eval_locals = {{
            "tool_name": tool_name,
            "tool_input": tool_input,
            "recent_tool_names": recent_tool_names,
            "recent_tool_inputs": recent_tool_inputs,
        }}
        # Restricted eval — no builtins, no globals beyond locals
        fires = bool(eval(DETECTION_EXPR, {{"__builtins__": {{}}}}, eval_locals))
    except Exception as exc:
        sys.stderr.write(f"[sio-promoted] detection eval failed: {{exc}}\\n")

    # Update rolling window AFTER evaluation so the current call doesn't
    # count toward its own "recent" history. Trim to WINDOW_SIZE.
    recent_tool_names.append(tool_name)
    recent_tool_inputs.append(tool_input)
    state["recent_tool_names"] = recent_tool_names[-WINDOW_SIZE:]
    state["recent_tool_inputs"] = recent_tool_inputs[-WINDOW_SIZE:]
    _save_state(session_id, state)

    if fires:
        msg = f"SIO promoted-rule: {{RULE_TEXT}}"
        if MODE == "block":
            sys.stdout.write(json.dumps({{"action": "block", "reason": msg}}))
            return
        # warn mode — log to stderr (visible in Claude Code's hook log) and allow
        sys.stderr.write(f"[sio-promoted-WARN] {{msg}}\\n")

    sys.stdout.write(json.dumps({{"action": "allow"}}))


if __name__ == "__main__":
    main()
'''


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


@dataclass
class HookGenerationResult:
    """Where the hook landed + the audit row id for sio rollback-hook."""

    hook_path: Path
    settings_path: Path
    promoted_hook_id: int
    slug: str


def _slugify(text: str, max_len: int = 60) -> str:
    """Filesystem-safe slug derived from rule text — used in the hook filename."""
    s = re.sub(r"[^A-Za-z0-9]+", "-", text.lower()).strip("-")
    return s[:max_len] or "unnamed-rule"


def generate_and_register(
    pattern: DetectionPattern,
    *,
    rule_text: str,
    rule_source_file: str,
    rule_source_line: int,
    mode: str = "warn",
    canonical_db_path: str | Path | None = None,
    claude_dir: str | Path | None = None,
    promoted_by: str = "sio promote-rule",
) -> HookGenerationResult:
    """Render the hook script, register it in settings.json, audit-row it.

    Args:
        pattern: The structured detection pattern from Phase 3.
        rule_text: The exact CLAUDE.md rule being promoted.
        rule_source_file / rule_source_line: provenance of the rule.
        mode: 'warn' (default) or 'block'.
        canonical_db_path: Override for ``~/.sio/sio.db`` (used by tests).
        claude_dir: Override for ``~/.claude/`` (used by tests).
        promoted_by: Free-form actor tag stored in ``promoted_hooks``.

    Returns:
        A :class:`HookGenerationResult` with the script path, the
        settings path that was modified, the slug, and the rowid of
        the new ``promoted_hooks`` audit row.

    Raises:
        ValueError: If ``pattern.promotable`` is False (caller should
            short-circuit before reaching this).
    """
    if not pattern.promotable:
        raise ValueError(
            "pattern is not promotable — extractor returned an empty matcher "
            "or detection_expr='False'. Caller should not reach this."
        )
    if mode not in ("warn", "block"):
        raise ValueError(f"mode must be 'warn' or 'block', got {mode!r}")

    claude_dir = Path(claude_dir) if claude_dir else Path.home() / ".claude"
    canonical_db_path = (
        Path(canonical_db_path)
        if canonical_db_path
        else Path(os.environ.get("SIO_DB_PATH", str(Path.home() / ".sio" / "sio.db")))
    )

    slug = _slugify(rule_text)
    hooks_dir = claude_dir / "hooks" / "sio-promoted"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    hook_path = hooks_dir / f"{slug}.py"

    promoted_at = datetime.now(timezone.utc).isoformat()

    # 1. Render the script.
    script = _HOOK_TEMPLATE.format(
        rule_text=rule_text,
        rule_source_file=rule_source_file,
        rule_source_line=rule_source_line,
        promoted_at=promoted_at,
        mode=mode,
        rationale=pattern.rationale,
        detection_expr=pattern.detection_expr,
        matcher_tools=pattern.matcher_tools,
    )
    hook_path.write_text(script, encoding="utf-8")
    hook_path.chmod(0o755)

    # 2. Register PreToolUse hook in settings.json (merge-not-overwrite,
    #    matching the same wrapped format ClaudeCodeAdapter.post_install
    #    uses for the SIO telemetry hooks).
    settings_path = claude_dir / "settings.json"
    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, ValueError):
            backup = settings_path.with_suffix(".json.bak")
            shutil.copy2(settings_path, backup)
            settings = {}
    else:
        settings = {}

    hooks = settings.setdefault("hooks", {})
    pre_tool_use = hooks.setdefault("PreToolUse", [])

    matcher = "|".join(pattern.matcher_tools) if pattern.matcher_tools else ""
    new_entry = {
        "matcher": matcher,
        "hooks": [
            {
                "type": "command",
                "command": f"{sys.executable} {hook_path}",
            }
        ],
    }

    # Idempotent: skip if a registration with this exact hook_path already
    # exists (matched on the absolute hook script path, not the full command,
    # so a different python interpreter still counts as "already there").
    already = False
    for entry in pre_tool_use:
        if not isinstance(entry, dict):
            continue
        for inner in entry.get("hooks", []):
            if isinstance(inner, dict) and str(hook_path) in inner.get("command", ""):
                already = True
                break
        if already:
            break

    if not already:
        pre_tool_use.append(new_entry)
        tmp = settings_path.with_suffix(".json.tmp")
        tmp.write_text(json.dumps(settings, indent=2), encoding="utf-8")
        tmp.replace(settings_path)

    # 3. Audit row in promoted_hooks. INSERT (not REPLACE) so re-promotion
    #    of the same rule produces a new row — useful for tracking mode
    #    flips (warn → block) over time.
    canonical_db_path.parent.mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(canonical_db_path) as conn:
        cur = conn.execute(
            "INSERT INTO promoted_hooks "
            "(rule_text, rule_source_file, rule_source_line, hook_event, "
            "hook_path, detection_pattern, mode, promoted_at, promoted_by) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (
                rule_text,
                rule_source_file,
                rule_source_line,
                "PreToolUse",
                str(hook_path),
                pattern.to_json_str(),
                mode,
                promoted_at,
                promoted_by,
            ),
        )
        promoted_hook_id = cur.lastrowid

    return HookGenerationResult(
        hook_path=hook_path,
        settings_path=settings_path,
        promoted_hook_id=promoted_hook_id,
        slug=slug,
    )
